import { StyleSheet } from 'react-native'
import { theme } from '..'

export function makeHomeStyles(c: any) {
  return StyleSheet.create({
    safe: {
      flex: 1,
      backgroundColor: c.bgPrimary,
    },
    container: {
      flex: 1,
      backgroundColor: c.bgPrimary,
    },
    content: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 32,
    },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 18,
    },
    logo: {
      fontFamily: theme.fonts.serif,
      fontSize: 30,
      color: c.accentRose,
      lineHeight: 34,
    },
    tagline: {
      marginTop: 2,
      fontFamily: theme.fonts.sans,
      fontSize: 10,
      letterSpacing: 1.2,
      color: c.textMuted,
    },
    avatar: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: c.borderRose,
      backgroundColor: c.bgSecondary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontFamily: theme.fonts.sansSemiBold,
      fontSize: 14,
      color: c.accentGold,
    },
    greetingBlock: {
      marginBottom: 18,
    },
    greeting: {
      fontFamily: theme.fonts.serifItalic,
      fontSize: 28,
      color: c.accentGold,
      textAlign: 'center',
      marginBottom: 4,
    },
    context: {
      fontFamily: theme.fonts.sans,
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
    },
    heroCard: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingVertical: 22,
      alignItems: 'center',
      marginBottom: 14,
      shadowColor: c.shadow,
      shadowOpacity: 0.25,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },
    phaseBadge: {
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: c.borderRose,
      backgroundColor: 'rgba(217,155,155,0.08)',
      marginBottom: 14,
    },
    phaseBadgeText: {
      fontFamily: theme.fonts.sansMedium,
      fontSize: 11,
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: c.accentRose,
    },
    heroTitle: {
      fontFamily: theme.fonts.serifSemiBold,
      fontSize: 26,
      color: c.accentGold,
      textAlign: 'center',
      marginBottom: 8,
    },
    heroMessage: {
      fontFamily: theme.fonts.sans,
      fontSize: 15,
      lineHeight: 23,
      color: c.textMuted,
      textAlign: 'center',
    },
    predictionRow: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      marginBottom: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    predictionLabel: {
      fontFamily: theme.fonts.sans,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: c.textMuted,
      marginBottom: 4,
    },
    predictionDate: {
      fontFamily: theme.fonts.sansSemiBold,
      fontSize: 22,
      color: c.accentRose,
    },
    confidencePill: {
      borderRadius: 999,
      paddingHorizontal: 12,
      paddingVertical: 7,
    },
    confidenceText: {
      fontFamily: theme.fonts.sansSemiBold,
      fontSize: 11,
    },
    confidenceHigh: {
      backgroundColor: 'rgba(155,168,141,0.18)',
    },
    confidenceMedium: {
      backgroundColor: 'rgba(243,229,216,0.12)',
    },
    confidenceLow: {
      backgroundColor: 'rgba(217,155,155,0.14)',
    },
    confidenceHighText: {
      color: c.accentSage,
    },
    confidenceMediumText: {
      color: c.accentGold,
    },
    confidenceLowText: {
      color: c.accentRose,
    },
    logBanner: {
      backgroundColor: c.accentRose,
      borderRadius: 14,
      paddingHorizontal: 18,
      paddingVertical: 18,
      marginBottom: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    logBannerText: {
      fontFamily: theme.fonts.sansSemiBold,
      fontSize: 16,
      color: c.bgPrimary,
    },
    shortcutRow: {
      gap: 8,
      paddingBottom: 2,
      marginBottom: 16,
    },
    shortcutBtn: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 12,
      paddingVertical: 10,
      paddingHorizontal: 14,
      alignItems: 'center',
      justifyContent: 'center',
      minWidth: 64,
      gap: 4,
    },
    shortcutIcon: {
      fontSize: 15,
      color: c.accentRose,
    },
    shortcutLabel: {
      fontFamily: theme.fonts.sans,
      fontSize: 11,
      color: c.textMuted,
    },
    statsRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 16,
    },
    statCard: {
      flex: 1,
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: 'center',
    },
    statLabel: {
      fontFamily: theme.fonts.sans,
      fontSize: 10,
      textTransform: 'uppercase',
      letterSpacing: 1,
      color: c.textMuted,
      marginBottom: 6,
    },
    statValue: {
      fontFamily: theme.fonts.serif,
      fontSize: 24,
      color: c.accentGold,
    },
    intelligenceCard: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 14,
      padding: 16,
      marginBottom: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
    },
    intelligenceIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(217,155,155,0.08)',
      borderWidth: 1,
      borderColor: c.borderRose,
    },
    intelligenceBody: {
      flex: 1,
    },
    intelligenceTitle: {
      fontFamily: theme.fonts.sansMedium,
      fontSize: 12,
      textTransform: 'uppercase',
      letterSpacing: 0.9,
      color: c.textMuted,
      marginBottom: 4,
    },
    intelligenceDesc: {
      fontFamily: theme.fonts.sans,
      fontSize: 14,
      lineHeight: 21,
      color: c.textPrimary,
    },
    quickActionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginBottom: 16,
    },
    quickActionCard: {
      width: '48.5%',
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 16,
      padding: 14,
      gap: 8,
    },
    quickActionTitle: {
      fontFamily: theme.fonts.serifSemiBold,
      fontSize: 22,
      color: c.accentGold,
    },
    quickActionDesc: {
      fontFamily: theme.fonts.sans,
      fontSize: 12,
      lineHeight: 18,
      color: c.textMuted,
    },

    ringHeroCard: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingTop: 20,
      paddingBottom: 24,
      alignItems: 'center',
      marginBottom: 14,
      shadowColor: c.shadow,
      shadowOpacity: 0.25,
      shadowRadius: 14,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    },

    ringWrap: {
      width: 220,
      height: 220,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },

    ringCenter: {
      position: 'absolute',
      alignItems: 'center',
      justifyContent: 'center',
    },

    ringCenterLabel: {
      fontFamily: theme.fonts.sans,
      fontSize: 12,
      letterSpacing: 1,
      textTransform: 'uppercase',
      color: c.textMuted,
      marginBottom: 4,
    },

    ringCenterValue: {
      fontFamily: theme.fonts.serifSemiBold,
      fontSize: 34,
      color: c.accentGold,
      lineHeight: 40,
      textAlign: 'center'
    },

    ringCenterSubLabel: {
      fontFamily: theme.fonts.sans,
      fontSize: 14,
      color: c.textMuted,
      marginTop: 4,
      textAlign: 'center',
    },

    ringCenterValueAlt: {
      fontFamily: theme.fonts.serifSemiBold,
      fontSize: 28,
      color: c.accentGold,
      lineHeight: 34,
      textAlign: 'center',
      maxWidth: 120,
    },
    
    emptyStateCard: {
      backgroundColor: c.bgSecondary,
      borderWidth: 1,
      borderColor: c.borderRose,
      borderRadius: 20,
      padding: 24,
      alignItems: 'center',
      gap: 12,
    },
    emptyStateIcon: {
      fontSize: 48,
      color: c.accentRose,
    },
  emptyStateTitle: {
    fontFamily: theme.fonts.serifSemiBold,
    fontSize: 24,
    color: c.accentGold,
    textAlign: 'center',
  },
  emptyStateDesc: {
    fontFamily: theme.fonts.sans,
    fontSize: 14,
    color: c.textMuted,
    textAlign: 'center',
    lineHeight: 22,
    paddingHorizontal: 8,
  },
  emptyStateBtn: {
    backgroundColor: c.accentRose,
    borderRadius: 14,
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    width: '100%',
    marginTop: 4,
  },
  emptyStateBtnText: {
    fontFamily: theme.fonts.sansSemiBold,
    fontSize: 15,
    color: c.bgPrimary,
  },
  emptyStateGrid: {
    flexDirection: 'row',
    gap: 10,
    width: '100%',
    marginTop: 8,
  },
  emptyStateGridCard: {
    flex: 1,
    backgroundColor: c.bgPrimary,
    borderWidth: 1,
    borderColor: c.borderRose,
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  emptyStateGridTitle: {
    fontFamily: theme.fonts.serifSemiBold,
    fontSize: 16,
    color: c.accentGold,
  },
  emptyStateGridDesc: {
    fontFamily: theme.fonts.sans,
    fontSize: 12,
    color: c.textMuted,
    lineHeight: 17,
  },


  })
}